export {
  GAME_SESSION_BASE_TRAY_CAPACITY,
  GAME_SESSION_MAX_TRAY_CAPACITY,
  GAME_SESSION_TRAY_CAPACITY,
  GameSession,
  type GameSessionDemagnetizeResult,
  type GameSessionMeltLocation,
  type GameSessionMeltResult,
  type GameSessionMagneticResolution,
  type GameSessionPendingSelectionResult,
  type GameSessionOptions,
  type GameSessionSelectionResult,
  type GameSessionSnapshot,
  type GameSessionStatus,
  type GameSessionTripleRemovalPlan,
  type GameSessionTripleRemovalResult,
  type GameSessionWildcardPlan,
  type GameSessionWildcardResolution,
  type GameSessionWildcardResult,
} from "@/games/dog-lege-dog/game/game-session";

export {
  BLOCK_HEIGHT,
  BLOCK_WIDTH,
  DOG_PATTERN_TYPES,
  FIRST_LEVEL,
  FIRST_LEVEL_GENERATOR_VERSION,
  FIRST_LEVEL_MAX_LAYERS,
  FIRST_LEVEL_NUMBER,
  FIRST_LEVEL_PATTERN_TYPES,
  FIRST_LEVEL_REWARD,
  FIRST_LEVEL_SEED,
} from "@/games/dog-lege-dog/levels/first-level";
export { getDogLegeDogLevel } from "@/games/dog-lege-dog/levels/level-provider";
export type {
  DogBlock,
  DogBoard,
  DogBoardCell,
  DogBoardShape,
  DogDifficultyRange,
  DogDifficultyTarget,
  DogDifficultyCertainty,
  DogLevelDifficulty,
  DogLevelGeneration,
  DogLevelGenerationFailure,
  DogLevelGeometry,
  DogLevelReplay,
  DogLevelReplayMode,
  DogLegeDogLevel,
  DogPatternType,
  DogSpecialMechanism,
  DogSpecialMechanismConfig,
  DogSpecialMechanismHandler,
  DogSpecialMechanismStateValue,
  DogTrayBlock,
  DogSafeChoiceSearchStatus,
  DogSolvabilityStatus,
} from "@/games/dog-lege-dog/levels/first-level";

export {
  DEFAULT_LEVEL_GENERATOR,
  DEFAULT_LEVEL_REWARD,
  DEFAULT_LEVEL_SEED,
  DOG_GAME_ID,
  DOG_SHAPE_TEMPLATES,
  calculateDifficultyMetrics,
  calculateDogLevelReward,
  DOG_LEVEL_REWARD_CONFIG,
  DOG_REWARD_CONFIG_VERSION,
  findSolvablePath,
  findSolvability,
  findSolvabilityFromState,
  getDifficultyTarget,
  getLevelDifficultyMetrics,
  LEVEL_GENERATOR_VERSION,
  MAX_LEVEL_NUMBER,
  MAX_LEVEL_GENERATION_ATTEMPTS,
  LevelGenerator,
  generateDogLegeDogLevel,
  getBlockCount,
  getMaxLayers,
  getPatternTypeCount,
  isDifficultyWithinTarget,
  isLevelSolvable,
  type LevelCandidateFilter,
  replayDogLegeDogLevel,
  replayDogLegeDogLevelAttempt,
  type DogShapeTemplate,
  type LevelGeneratorOptions,
  type LevelGeneratorRequest,
  type DogLevelRewardConfig,
  type SolvabilityResult,
  type SolvabilitySearchOptions,
  type SolvabilityStateOptions,
} from "@/games/dog-lege-dog/levels/level-generator";
export { createRunSeed } from "@/games/dog-lege-dog/levels/level-random";
export {
  DOG_FREEZE_GENERATOR_VERSION,
  DOG_ILLUSION_GENERATOR_VERSION,
  DOG_LEVEL_SPECIAL_MECHANISM_DEFINITIONS,
} from "@/games/dog-lege-dog/game/game-config";

export {
  DOG_FREEZE_MECHANISM_TYPE,
  DOG_FREEZE_MELT_TRIPLE_COUNT,
  DOG_ILLUSION_MECHANISM_TYPE,
  DOG_ILLUSION_MASK_STATUS,
  DOG_MAGNETIC_MECHANISM_TYPE,
  DOG_TWIN_MECHANISM_TYPE,
  DOG_SPECIAL_MECHANISM_DENSITY_LIMIT,
  DOG_SPECIAL_MECHANISM_MIDDLE_LAYER_RATIO,
  DOG_SPECIAL_MECHANISM_HANDLERS,
  assignDogSpecialMechanisms,
  createDogSpecialMechanism,
  createDogIllusionMechanism,
  createDogSpecialMechanismHandlerMap,
  getDogBlockLogicalUnitCount,
  getDogLogicalBlockCount,
  getDogTrayLogicalUnitCount,
  getDogSpecialMechanismLogicalUnitWeight,
  getDogSpecialMechanismComposition,
  getDogIllusionDisguisedPattern,
  getDogSpecialMechanismConfigs,
  getDogSpecialMechanismConfigsForGeneration,
  limitDogSpecialMechanismConfigsForLogicalDensity,
  selectDogSpecialMechanismCounts,
  validateDogSpecialMechanismComposition,
} from "@/games/dog-lege-dog/game/special-mechanisms";
export type {
  DogSpecialMechanismAssignmentOptions,
  DogSpecialMechanismComposition,
} from "@/games/dog-lege-dog/game/special-mechanisms";

export {
  DOG_ITEM_DEFINITIONS,
  DOG_ITEM_IDS,
  DOG_LOADOUT_SIZE,
  areDogLoadoutsEqual,
  getDogItemDefinition,
  isDogItemId,
  isValidDogLoadout,
  normalizeDogLoadout,
  type DogItemDefinition,
  type DogItemId,
  type DogLoadoutSummaryItemState,
  type DogItemTargetType,
  type DogItemVisualFeedback,
} from "@/games/dog-lege-dog/game/dog-loadout";

export {
  DOG_ITEM_RUNTIME_DEFINITIONS,
  DogItemRuntime,
  type DogItemAnimationCompletion,
  type DogItemEffect,
  getDogItemUses,
  type DogItemActionResult,
  type DogItemAvailabilityContext,
  type DogItemExecutionContext,
  type DogItemExecutionResult,
  type DogItemRuntimeDefinition,
  type DogItemRuntimeOptions,
  type DogItemRuntimePhase,
  type DogItemRuntimeSnapshot,
  type DogItemState,
  type DogItemTarget,
} from "@/games/dog-lege-dog/game/dog-item-runtime";

export { createDogLegeDogGame, startDogLegeDogGame } from "@/games/dog-lege-dog/game/game-controller";
export type {
  DogLegeDogGame,
  DogLegeDogGameOptions,
  DogLegeDogGameState,
  DogVisualFeedback,
} from "@/games/dog-lege-dog/game/game-types";
